export const THEME_COLORS = {
  lightBackground: "oklch(1 0 0)",
  darkBackground: "oklch(0.105 0 0)",
} as const;

export const CHART_TOKENS = {
  animationDurationMs: 220,
  barRadius: [6, 6, 0, 0] as [number, number, number, number],
  moduleHeightClass: "h-56",
  compactMargin: { left: -24, right: 8, top: 8, bottom: 0 },
  tooltipPayloadLimit: 8,
} as const;

export const FEEDBACK_TOKENS = {
  undoToastDurationMs: 12_000,
} as const;

export const SOCIAL_IMAGE_TOKENS = {
  width: 1200,
  height: 630,
  background: "#fbfaf7",
  surface: "#ffffff",
  ink: "#183027",
  muted: "#5e6a63",
  border: "#dcd8cf",
  primary: "#008b5f",
  metroRed: "#d6232a",
  metroBlue: "#2464b4",
  heatFresco: "#3b92d1",
  heatCalor: "#d99100",
  heatInfierno: "#cf3a24",
  logoContainerPx: 64,
  logoMarkPx: 50,
  logoStemWidthPx: 14,
  logoBulbPx: 28,
  logoBulbBorderPx: 4,
  logoHighlightWidthPx: 4,
  logoHighlightHeightPx: 22,
  logoHighlightOpacity: 0.75,
  logoGapPx: 20,
  headerTitlePx: 30,
  headerTextPx: 20,
  descriptionPx: 26,
  navMenuPx: 44,
  navMenuLineWidthPx: 24,
  navMenuLineHeightPx: 3,
  trainWidthPx: 330,
  trainHeightPx: 100,
  trainOpacity: 0.28,
  actionPaddingBlockPx: 10,
  actionPaddingInlinePx: 24,
  actionRowWidthPx: 780,
  actionIconPx: 36,
  actionTitlePx: 22,
  actionDescriptionPx: 16,
  actionGapPx: 10,
  actionBarWidthPx: 7,
  actionBarSmPx: 24,
  actionBarMdPx: 36,
  actionBarLgPx: 30,
  radiusPx: 16,
  markRadiusPx: 12,
  pillRadiusPx: 999,
  paddingPx: 48,
  cardPaddingPx: 18,
  sectionGapPx: 24,
  stackGapPx: 8,
  textMaxWidthPx: 940,
  logoBorderPx: 2,
  markRotationDeg: 45,
  descriptionLineHeight: 1.22,
} as const;
