insert into public.metro_stations (line, station_id, name, sort_order)
values
  ('L1', 'pinar-de-chamartin', 'Pinar de Chamartín', 0),
  ('L1', 'bambu', 'Bambú', 1),
  ('L1', 'chamartin', 'Chamartín', 2),
  ('L1', 'plaza-de-castilla', 'Plaza de Castilla', 3),
  ('L1', 'valdeacederas', 'Valdeacederas', 4),
  ('L1', 'tetuan', 'Tetuán', 5),
  ('L1', 'estrecho', 'Estrecho', 6),
  ('L1', 'alvarado', 'Alvarado', 7),
  ('L1', 'cuatro-caminos', 'Cuatro Caminos', 8),
  ('L1', 'rios-rosas', 'Ríos Rosas', 9),
  ('L1', 'iglesia', 'Iglesia', 10),
  ('L1', 'bilbao', 'Bilbao', 11),
  ('L1', 'tribunal', 'Tribunal', 12),
  ('L1', 'gran-via', 'Gran Vía', 13),
  ('L1', 'sol', 'Sol', 14),
  ('L1', 'tirso-de-molina', 'Tirso de Molina', 15),
  ('L1', 'anton-martin', 'Antón Martín', 16),
  ('L1', 'estacion-del-arte', 'Estación del Arte', 17),
  ('L1', 'atocha', 'Atocha', 18),
  ('L1', 'menendez-pelayo', 'Menéndez Pelayo', 19),
  ('L1', 'pacifico', 'Pacífico', 20),
  ('L1', 'puente-de-vallecas', 'Puente de Vallecas', 21),
  ('L1', 'nueva-numancia', 'Nueva Numancia', 22),
  ('L1', 'portazgo', 'Portazgo', 23),
  ('L1', 'buenos-aires', 'Buenos Aires', 24),
  ('L1', 'alto-del-arenal', 'Alto del Arenal', 25),
  ('L1', 'miguel-hernandez', 'Miguel Hernández', 26),
  ('L1', 'sierra-de-guadalupe', 'Sierra de Guadalupe', 27),
  ('L1', 'villa-de-vallecas', 'Villa de Vallecas', 28),
  ('L1', 'congosto', 'Congosto', 29),
  ('L1', 'la-gavia', 'La Gavia', 30),
  ('L1', 'las-suertes', 'Las Suertes', 31),
  ('L1', 'valdecarros', 'Valdecarros', 32),
  ('L2', 'las-rosas', 'Las Rosas', 0),
  ('L2', 'avenida-de-guadalajara', 'Avenida de Guadalajara', 1),
  ('L2', 'alsacia', 'Alsacia', 2),
  ('L2', 'la-almudena', 'La Almudena', 3),
  ('L2', 'la-elipa', 'La Elipa', 4),
  ('L2', 'ventas', 'Ventas', 5),
  ('L2', 'manuel-becerra', 'Manuel Becerra', 6),
  ('L2', 'goya', 'Goya', 7),
  ('L2', 'principe-de-vergara', 'Príncipe de Vergara', 8),
  ('L2', 'retiro', 'Retiro', 9),
  ('L2', 'banco-de-espana', 'Banco de España', 10),
  ('L2', 'sevilla', 'Sevilla', 11),
  ('L2', 'sol', 'Sol', 12),
  ('L2', 'opera', 'Ópera', 13),
  ('L2', 'santo-domingo', 'Santo Domingo', 14),
  ('L2', 'noviciado', 'Noviciado', 15),
  ('L2', 'san-bernardo', 'San Bernardo', 16),
  ('L2', 'quevedo', 'Quevedo', 17),
  ('L2', 'canal', 'Canal', 18),
  ('L2', 'cuatro-caminos', 'Cuatro Caminos', 19),
  ('L3', 'el-casar', 'El Casar', 0),
  ('L3', 'villaverde-alto', 'Villaverde Alto', 1),
  ('L3', 'san-cristobal', 'San Cristóbal', 2),
  ('L3', 'villaverde-bajo-cruce', 'Villaverde Bajo - Cruce', 3),
  ('L3', 'ciudad-de-los-angeles', 'Ciudad de los Ángeles', 4),
  ('L3', 'san-fermin-orcasur', 'San Fermín - Orcasur', 5),
  ('L3', 'hospital-12-de-octubre', 'Hospital 12 de Octubre', 6),
  ('L3', 'almendrales', 'Almendrales', 7),
  ('L3', 'legazpi', 'Legazpi', 8),
  ('L3', 'delicias', 'Delicias', 9),
  ('L3', 'palos-de-la-frontera', 'Palos de la Frontera', 10),
  ('L3', 'embajadores', 'Embajadores', 11),
  ('L3', 'lavapies', 'Lavapiés', 12),
  ('L3', 'sol', 'Sol', 13),
  ('L3', 'callao', 'Callao', 14),
  ('L3', 'plaza-de-espana', 'Plaza de España', 15),
  ('L3', 'ventura-rodriguez', 'Ventura Rodríguez', 16),
  ('L3', 'arguelles', 'Argüelles', 17),
  ('L3', 'moncloa', 'Moncloa', 18),
  ('L4', 'arguelles', 'Argüelles', 0),
  ('L4', 'san-bernardo', 'San Bernardo', 1),
  ('L4', 'bilbao', 'Bilbao', 2),
  ('L4', 'alonso-martinez', 'Alonso Martínez', 3),
  ('L4', 'colon', 'Colón', 4),
  ('L4', 'serrano', 'Serrano', 5),
  ('L4', 'velazquez', 'Velázquez', 6),
  ('L4', 'goya', 'Goya', 7),
  ('L4', 'lista', 'Lista', 8),
  ('L4', 'diego-de-leon', 'Diego de León', 9),
  ('L4', 'avenida-de-america', 'Avenida de América', 10),
  ('L4', 'prosperidad', 'Prosperidad', 11),
  ('L4', 'alfonso-xiii', 'Alfonso XIII', 12),
  ('L4', 'avenida-de-la-paz', 'Avenida de la Paz', 13),
  ('L4', 'arturo-soria', 'Arturo Soria', 14),
  ('L4', 'esperanza', 'Esperanza', 15),
  ('L4', 'canillas', 'Canillas', 16),
  ('L4', 'mar-de-cristal', 'Mar de Cristal', 17),
  ('L4', 'san-lorenzo', 'San Lorenzo', 18),
  ('L4', 'parque-de-santa-maria', 'Parque de Santa María', 19),
  ('L4', 'hortaleza', 'Hortaleza', 20),
  ('L4', 'manoteras', 'Manoteras', 21),
  ('L4', 'pinar-de-chamartin', 'Pinar de Chamartín', 22),
  ('L5', 'alameda-de-osuna', 'Alameda de Osuna', 0),
  ('L5', 'el-capricho', 'El Capricho', 1),
  ('L5', 'canillejas', 'Canillejas', 2),
  ('L5', 'torre-arias', 'Torre Arias', 3),
  ('L5', 'suanzes', 'Suanzes', 4),
  ('L5', 'ciudad-lineal', 'Ciudad Lineal', 5),
  ('L5', 'pueblo-nuevo', 'Pueblo Nuevo', 6),
  ('L5', 'quintana', 'Quintana', 7),
  ('L5', 'el-carmen', 'El Carmen', 8),
  ('L5', 'ventas', 'Ventas', 9),
  ('L5', 'diego-de-leon', 'Diego de León', 10),
  ('L5', 'nunez-de-balboa', 'Núñez de Balboa', 11),
  ('L5', 'ruben-dario', 'Rubén Darío', 12),
  ('L5', 'alonso-martinez', 'Alonso Martínez', 13),
  ('L5', 'chueca', 'Chueca', 14),
  ('L5', 'gran-via', 'Gran Vía', 15),
  ('L5', 'callao', 'Callao', 16),
  ('L5', 'opera', 'Ópera', 17),
  ('L5', 'la-latina', 'La Latina', 18),
  ('L5', 'puerta-de-toledo', 'Puerta de Toledo', 19),
  ('L5', 'acacias', 'Acacias', 20),
  ('L5', 'piramides', 'Pirámides', 21),
  ('L5', 'marques-de-vadillo', 'Marqués de Vadillo', 22),
  ('L5', 'urgel', 'Urgel', 23),
  ('L5', 'oporto', 'Oporto', 24),
  ('L5', 'vista-alegre', 'Vista Alegre', 25),
  ('L5', 'carabanchel', 'Carabanchel', 26),
  ('L5', 'eugenia-de-montijo', 'Eugenia de Montijo', 27),
  ('L5', 'aluche', 'Aluche', 28),
  ('L5', 'empalme', 'Empalme', 29),
  ('L5', 'campamento', 'Campamento', 30),
  ('L5', 'casa-de-campo', 'Casa de Campo', 31),
  ('L6', 'laguna', 'Laguna', 0),
  ('L6', 'carpetana', 'Carpetana', 1),
  ('L6', 'oporto', 'Oporto', 2),
  ('L6', 'opanel', 'Opañel', 3),
  ('L6', 'plaza-eliptica', 'Plaza Elíptica', 4),
  ('L6', 'usera', 'Usera', 5),
  ('L6', 'legazpi', 'Legazpi', 6),
  ('L6', 'arganzuela-planetario', 'Arganzuela - Planetario', 7),
  ('L6', 'mendez-alvaro', 'Méndez Álvaro', 8),
  ('L6', 'pacifico', 'Pacífico', 9),
  ('L6', 'conde-de-casal', 'Conde de Casal', 10),
  ('L6', 'sainz-de-baranda', 'Sainz de Baranda', 11),
  ('L6', 'o-donnell', 'O''Donnell', 12),
  ('L6', 'manuel-becerra', 'Manuel Becerra', 13),
  ('L6', 'diego-de-leon', 'Diego de León', 14),
  ('L6', 'avenida-de-america', 'Avenida de América', 15),
  ('L6', 'republica-argentina', 'República Argentina', 16),
  ('L6', 'nuevos-ministerios', 'Nuevos Ministerios', 17),
  ('L6', 'cuatro-caminos', 'Cuatro Caminos', 18),
  ('L6', 'guzman-el-bueno', 'Guzmán el Bueno', 19),
  ('L6', 'vicente-aleixandre', 'Vicente Aleixandre', 20),
  ('L6', 'ciudad-universitaria', 'Ciudad Universitaria', 21),
  ('L6', 'moncloa', 'Moncloa', 22),
  ('L6', 'arguelles', 'Argüelles', 23),
  ('L6', 'principe-pio', 'Príncipe Pío', 24),
  ('L6', 'puerta-del-angel', 'Puerta del Ángel', 25),
  ('L6', 'alto-de-extremadura', 'Alto de Extremadura', 26),
  ('L6', 'lucero', 'Lucero', 27),
  ('L7', 'hospital-del-henares', 'Hospital del Henares', 0),
  ('L7', 'henares', 'Henares', 1),
  ('L7', 'jarama', 'Jarama', 2),
  ('L7', 'san-fernando', 'San Fernando', 3),
  ('L7', 'la-rambla', 'La Rambla', 4),
  ('L7', 'coslada-central', 'Coslada Central', 5),
  ('L7', 'barrio-del-puerto', 'Barrio del Puerto', 6),
  ('L7', 'estadio-metropolitano', 'Estadio Metropolitano', 7),
  ('L7', 'las-musas', 'Las Musas', 8),
  ('L7', 'san-blas', 'San Blas', 9),
  ('L7', 'simancas', 'Simancas', 10),
  ('L7', 'garcia-noblejas', 'García Noblejas', 11),
  ('L7', 'ascao', 'Ascao', 12),
  ('L7', 'pueblo-nuevo', 'Pueblo Nuevo', 13),
  ('L7', 'barrio-de-la-concepcion', 'Barrio de la Concepción', 14),
  ('L7', 'parque-de-las-avenidas', 'Parque de las Avenidas', 15),
  ('L7', 'cartagena', 'Cartagena', 16),
  ('L7', 'avenida-de-america', 'Avenida de América', 17),
  ('L7', 'gregorio-maranon', 'Gregorio Marañón', 18),
  ('L7', 'alonso-cano', 'Alonso Cano', 19),
  ('L7', 'canal', 'Canal', 20),
  ('L7', 'islas-filipinas', 'Islas Filipinas', 21),
  ('L7', 'guzman-el-bueno', 'Guzmán el Bueno', 22),
  ('L7', 'francos-rodriguez', 'Francos Rodríguez', 23),
  ('L7', 'valdezarza', 'Valdezarza', 24),
  ('L7', 'antonio-machado', 'Antonio Machado', 25),
  ('L7', 'penagrande', 'Peñagrande', 26),
  ('L7', 'avenida-de-la-ilustracion', 'Avenida de la Ilustración', 27),
  ('L7', 'lacoma', 'Lacoma', 28),
  ('L7', 'arroyofresno', 'Arroyofresno', 29),
  ('L7', 'pitis', 'Pitis', 30),
  ('L8', 'nuevos-ministerios', 'Nuevos Ministerios', 0),
  ('L8', 'colombia', 'Colombia', 1),
  ('L8', 'pinar-del-rey', 'Pinar del Rey', 2),
  ('L8', 'mar-de-cristal', 'Mar de Cristal', 3),
  ('L8', 'feria-de-madrid', 'Feria de Madrid', 4),
  ('L8', 'aeropuerto-t1-t2-t3', 'Aeropuerto T1-T2-T3', 5),
  ('L8', 'barajas', 'Barajas', 6),
  ('L8', 'aeropuerto-t4', 'Aeropuerto T4', 7),
  ('L9', 'paco-de-lucia', 'Paco de Lucía', 0),
  ('L9', 'mirasierra', 'Mirasierra', 1),
  ('L9', 'herrera-oria', 'Herrera Oria', 2),
  ('L9', 'barrio-del-pilar', 'Barrio del Pilar', 3),
  ('L9', 'ventilla', 'Ventilla', 4),
  ('L9', 'plaza-de-castilla', 'Plaza de Castilla', 5),
  ('L9', 'duque-de-pastrana', 'Duque de Pastrana', 6),
  ('L9', 'pio-xii', 'Pío XII', 7),
  ('L9', 'colombia', 'Colombia', 8),
  ('L9', 'concha-espina', 'Concha Espina', 9),
  ('L9', 'cruz-del-rayo', 'Cruz del Rayo', 10),
  ('L9', 'avenida-de-america', 'Avenida de América', 11),
  ('L9', 'nunez-de-balboa', 'Núñez de Balboa', 12),
  ('L9', 'principe-de-vergara', 'Príncipe de Vergara', 13),
  ('L9', 'ibiza', 'Ibiza', 14),
  ('L9', 'sainz-de-baranda', 'Sainz de Baranda', 15),
  ('L9', 'estrella', 'Estrella', 16),
  ('L9', 'vinateros', 'Vinateros', 17),
  ('L9', 'artilleros', 'Artilleros', 18),
  ('L9', 'pavones', 'Pavones', 19),
  ('L9', 'valdebernardo', 'Valdebernardo', 20),
  ('L9', 'vicalvaro', 'Vicálvaro', 21),
  ('L9', 'san-cipriano', 'San Cipriano', 22),
  ('L9', 'puerta-de-arganda', 'Puerta de Arganda', 23),
  ('L9', 'rivas-urbanizaciones', 'Rivas Urbanizaciones', 24),
  ('L9', 'rivas-futura', 'Rivas Futura', 25),
  ('L9', 'rivas-vaciamadrid', 'Rivas Vaciamadrid', 26),
  ('L9', 'la-poveda', 'La Poveda', 27),
  ('L9', 'arganda-del-rey', 'Arganda del Rey', 28),
  ('L10', 'hospital-infanta-sofia', 'Hospital Infanta Sofía', 0),
  ('L10', 'reyes-catolicos', 'Reyes Católicos', 1),
  ('L10', 'baunatal', 'Baunatal', 2),
  ('L10', 'manuel-de-falla', 'Manuel de Falla', 3),
  ('L10', 'marques-de-la-valdavia', 'Marqués de la Valdavia', 4),
  ('L10', 'la-moraleja', 'La Moraleja', 5),
  ('L10', 'la-granja', 'La Granja', 6),
  ('L10', 'ronda-de-la-comunicacion', 'Ronda de la Comunicación', 7),
  ('L10', 'las-tablas', 'Las Tablas', 8),
  ('L10', 'montecarmelo', 'Montecarmelo', 9),
  ('L10', 'tres-olivos', 'Tres Olivos', 10),
  ('L10', 'fuencarral', 'Fuencarral', 11),
  ('L10', 'begona', 'Begoña', 12),
  ('L10', 'chamartin', 'Chamartín', 13),
  ('L10', 'plaza-de-castilla', 'Plaza de Castilla', 14),
  ('L10', 'cuzco', 'Cuzco', 15),
  ('L10', 'santiago-bernabeu', 'Santiago Bernabéu', 16),
  ('L10', 'nuevos-ministerios', 'Nuevos Ministerios', 17),
  ('L10', 'gregorio-maranon', 'Gregorio Marañón', 18),
  ('L10', 'alonso-martinez', 'Alonso Martínez', 19),
  ('L10', 'tribunal', 'Tribunal', 20),
  ('L10', 'plaza-de-espana', 'Plaza de España', 21),
  ('L10', 'principe-pio', 'Príncipe Pío', 22),
  ('L10', 'lago', 'Lago', 23),
  ('L10', 'batan', 'Batán', 24),
  ('L10', 'casa-de-campo', 'Casa de Campo', 25),
  ('L10', 'colonia-jardin', 'Colonia Jardín', 26),
  ('L10', 'aviacion-espanola', 'Aviación Española', 27),
  ('L10', 'cuatro-vientos', 'Cuatro Vientos', 28),
  ('L10', 'joaquin-vilumbrales', 'Joaquín Vilumbrales', 29),
  ('L10', 'puerta-del-sur', 'Puerta del Sur', 30),
  ('L11', 'plaza-eliptica', 'Plaza Elíptica', 0),
  ('L11', 'abrantes', 'Abrantes', 1),
  ('L11', 'pan-bendito', 'Pan Bendito', 2),
  ('L11', 'san-francisco', 'San Francisco', 3),
  ('L11', 'carabanchel-alto', 'Carabanchel Alto', 4),
  ('L11', 'la-peseta', 'La Peseta', 5),
  ('L11', 'la-fortuna', 'La Fortuna', 6),
  ('L12', 'puerta-del-sur', 'Puerta del Sur', 0),
  ('L12', 'parque-lisboa', 'Parque Lisboa', 1),
  ('L12', 'alcorcon-central', 'Alcorcón Central', 2),
  ('L12', 'parque-oeste', 'Parque Oeste', 3),
  ('L12', 'universidad-rey-juan-carlos', 'Universidad Rey Juan Carlos', 4),
  ('L12', 'mostoles-central', 'Móstoles Central', 5),
  ('L12', 'pradillo', 'Pradillo', 6),
  ('L12', 'hospital-de-mostoles', 'Hospital de Móstoles', 7),
  ('L12', 'manuela-malasana', 'Manuela Malasaña', 8),
  ('L12', 'loranca', 'Loranca', 9),
  ('L12', 'hospital-de-fuenlabrada', 'Hospital de Fuenlabrada', 10),
  ('L12', 'parque-europa', 'Parque Europa', 11),
  ('L12', 'fuenlabrada-central', 'Fuenlabrada Central', 12),
  ('L12', 'parque-de-los-estados', 'Parque de los Estados', 13),
  ('L12', 'arroyo-culebro', 'Arroyo Culebro', 14),
  ('L12', 'conservatorio', 'Conservatorio', 15),
  ('L12', 'alonso-de-mendoza', 'Alonso de Mendoza', 16),
  ('L12', 'getafe-central', 'Getafe Central', 17),
  ('L12', 'juan-de-la-cierva', 'Juan de la Cierva', 18),
  ('L12', 'el-casar', 'El Casar', 19),
  ('L12', 'los-espartales', 'Los Espartales', 20),
  ('L12', 'el-bercial', 'El Bercial', 21),
  ('L12', 'el-carrascal', 'El Carrascal', 22),
  ('L12', 'julian-besteiro', 'Julián Besteiro', 23),
  ('L12', 'casa-del-reloj', 'Casa del Reloj', 24),
  ('L12', 'hospital-severo-ochoa', 'Hospital Severo Ochoa', 25),
  ('L12', 'leganes-central', 'Leganés Central', 26),
  ('L12', 'san-nicasio', 'San Nicasio', 27)
on conflict (line, station_id) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = true;
